const MISSING_STICKER = "data:image/svg+xml;charset=UTF-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 360 480'%3E%3Crect width='360' height='480' fill='%23e8eef4'/%3E%3Ctext x='180' y='240' text-anchor='middle' font-family='Arial,sans-serif' font-size='28' fill='%23566778'%3ESin foto%3C/text%3E%3C/svg%3E";

export const STICKER_ASSETS = {
// ALG — fotos reales validadas visualmente
"ALG1": "/stickers/ALG01.jpg",
"ALG2": "/stickers/ALG04.jpg",
"ALG3": "/stickers/ALG09.jpg",
"ALG4": "/stickers/ALG11.jpg",
"ALG5": "/stickers/ALG15.jpg",
"ALG8": "/stickers/ALG05.jpg",
"ALG9": "/stickers/ALG16.jpg",
"ALG10": "/stickers/ALG02.jpg",
"ALG11": "/stickers/ALG07.jpg",
"ALG12": "/stickers/ALG14.jpg",
"ALG14": "/stickers/ALG03.jpg",
"ALG15": "/stickers/ALG10.jpg",
"ALG16": "/stickers/ALG13.jpg",
"ALG17": "/stickers/ALG06.jpg",
"ALG18": "/stickers/ALG12.jpg",
"ALG19": "/stickers/ALG08.jpg",

// ARG — fotos reales validadas visualmente
"ARG1": "/stickers/ARG1.jpg",
"ARG2": "/stickers/ARG2.jpg",
"ARG3": "/stickers/ARG3.jpg",
"ARG4": "/stickers/ARG4.jpg",
"ARG5": "/stickers/ARG5.jpg",
"ARG6": "/stickers/ARG6.jpg",
"ARG7": "/stickers/ARG7.jpg",
"ARG8": "/stickers/ARG8.jpg",
"ARG9": "/stickers/ARG9.jpg",
"ARG10": "/stickers/ARG10.jpg",
"ARG11": "/stickers/ARG11.jpg",
"ARG12": "/stickers/ARG12.jpg",
"ARG13": "/stickers/ARG13.jpg",
"ARG14": "/stickers/ARG14.jpg",
"ARG15": "/stickers/ARG15.jpg",
"ARG16": "/stickers/ARG16.jpg",
"ARG17": "/stickers/ARG17.jpg",
"ARG18": "/stickers/ARG18.jpg",
"ARG19": "/stickers/ARG19.jpg",
"ARG20": "/stickers/ARG20.jpg",

// AUT — fotos reales validadas visualmente
"AUT1": "/stickers/AUT01.png",
"AUT2": "/stickers/AUT07.png",
"AUT3": "/stickers/AUT12.png",
"AUT4": "/stickers/AUT05.png",
"AUT5": "/stickers/AUT06.png",
"AUT6": "/stickers/AUT10.png",
"AUT7": "/stickers/AUT16.png",
"AUT9": "/stickers/AUT08.png",
"AUT10": "/stickers/AUT11.png",
"AUT11": "/stickers/AUT04.png",
"AUT12": "/stickers/AUT09.png",
"AUT15": "/stickers/AUT13.png",
"AUT16": "/stickers/AUT14.png",
"AUT17": "/stickers/AUT15.png",
"AUT18": "/stickers/AUT03.png",
"AUT19": "/stickers/AUT02.png",

// BEL — fotos reales validadas visualmente
"BEL1": "/stickers/BEL01.png",
"BEL3": "/stickers/BEL04.png",
"BEL4": "/stickers/BEL10.png",
"BEL5": "/stickers/BEL07.png",
"BEL6": "/stickers/BEL03.png",
"BEL7": "/stickers/BEL12.png",
"BEL8": "/stickers/BEL09.png",
"BEL9": "/stickers/BEL08.png",
"BEL10": "/stickers/BEL05.png",
"BEL11": "/stickers/BEL14.png",
"BEL12": "/stickers/BEL06.png",
"BEL14": "/stickers/BEL02.png",
"BEL15": "/stickers/BEL16.png",
"BEL16": "/stickers/BEL15.png",
"BEL19": "/stickers/BEL13.png",
"BEL20": "/stickers/BEL11.png",

// BIH — fotos reales validadas visualmente
"BIH1": "/stickers/BIH01.png",
"BIH2": "/stickers/BIH10.png",
"BIH4": "/stickers/BIH07.png",
"BIH5": "/stickers/BIH06.png",
"BIH6": "/stickers/BIH11.png",
"BIH8": "/stickers/BIH02.png",
"BIH9": "/stickers/BIH03.png",
"BIH11": "/stickers/BIH08.png",
"BIH12": "/stickers/BIH12.png",
"BIH16": "/stickers/BIH04.png",
"BIH18": "/stickers/BIH05.png",
"BIH19": "/stickers/BIH09.png",
"BIH20": "/stickers/BIH13.png",

// CAN — fotos reales validadas visualmente
"CAN1": "/stickers/CAN01.png",
"CAN2": "/stickers/CAN04.png",
"CAN3": "/stickers/CAN02.png",
"CAN5": "/stickers/CAN09.png",
"CAN7": "/stickers/CAN05.png",
"CAN8": "/stickers/CAN15.png",
"CAN9": "/stickers/CAN11.png",
"CAN10": "/stickers/CAN07.png",
"CAN11": "/stickers/CAN06.png",
"CAN12": "/stickers/CAN13.png",
"CAN15": "/stickers/CAN10.png",
"CAN17": "/stickers/CAN08.png",
"CAN18": "/stickers/CAN12.png",
"CAN19": "/stickers/CAN03.png",
"CAN20": "/stickers/CAN14.png",

// CIV — material real disponible
"CIV1": "/stickers/CIV1.jpg",

// COD — material real validado por nombre impreso
"COD1": "/stickers/COD1.jpg",
"COD3": "/stickers/COD7.jpg",
"COD5": MISSING_STICKER, // COD5.jpg contiene Meschack Elia, no Arthur Masuaku
"COD6": "/stickers/COD3.jpg",
"COD7": MISSING_STICKER, // COD7.jpg contiene Aaron Wan-Bissaka, no Joris Kayembe
"COD8": "/stickers/COD8.jpg",
"COD15": "/stickers/COD5.jpg",

// CPV — material real disponible
"CPV2": "/stickers/CPV2.jpg",

// CRO — se descartan CRO3.jpg, CRO5.jpg y CRO8.jpg por pertenecer a otras selecciones
"CRO3": MISSING_STICKER,
"CRO4": "/stickers/CRO4.jpg",
"CRO5": MISSING_STICKER,
"CRO6": "/stickers/CRO6.jpg",
"CRO8": "/stickers/CRO9.jpg",
"CRO9": MISSING_STICKER, // CRO9.jpg contiene Kristijan Jakić, no Luka Modrić
"CRO18": "/stickers/CRO18.jpg",

// CUW — material real disponible
"CUW1": "/stickers/CUW1.jpg",
"CUW19": "/stickers/CUW19.jpg",

// CZE — material real disponible
"CZE1": "/stickers/CZE1.jpg",

"BRA1": "/stickers/BRA01.png",
"BRA2": "/stickers/BRA03.png",
"BRA3": "/stickers/BRA04.png",
"BRA4": "/stickers/BRA05.png",
"BRA5": "/stickers/BRA07.png",
"BRA6": "/stickers/BRA08.png",
"BRA7": "/stickers/BRA09.png",
"BRA8": "/stickers/BRA06.png",
"BRA9": "/stickers/BRA11.png",
"BRA10": "/stickers/BRA12.png",
"BRA11": "/stickers/BRA10.png",
"BRA12": "/stickers/BRA13.png",
"BRA13": "/stickers/BRA02.png",
"BRA14": "/stickers/BRA14.png",
"BRA15": "/stickers/BRA19.png",
"BRA16": "/stickers/BRA20.png",
"BRA17": "/stickers/BRA18.png",
"BRA18": "/stickers/BRA15.png",
"BRA19": "/stickers/BRA16.png",
"BRA20": "/stickers/BRA17.png",
"COL1": "/stickers/COL01.png",
"COL2": "/stickers/COL04.png",
"COL3": "/stickers/COL03.png",
"COL4": "/stickers/COL19.png",
"COL5": "/stickers/COL17.png",
"COL6": "/stickers/COL16.png",
"COL7": "/stickers/COL18.png",
"COL8": "/stickers/COL20.png",
"COL9": "/stickers/COL15.png",
"COL10": "/stickers/COL14.png",
"COL11": "/stickers/COL13.png",
"COL12": "/stickers/COL10.png",
"COL13": "/stickers/COL02.png",
"COL14": "/stickers/COL12.png",
"COL15": "/stickers/COL11.png",
"COL16": "/stickers/COL09.png",
"COL17": "/stickers/COL07.png",
"COL18": "/stickers/COL06.png",
"COL19": "/stickers/COL08.png",
"COL20": "/stickers/COL05.png",
"ECU1": "/stickers/ECU01.png",
"ECU2": "/stickers/ECU03.png",
"ECU3": "/stickers/ECU04.png",
"ECU4": "/stickers/ECU19.png",
"ECU5": "/stickers/ECU17.png",
"ECU6": "/stickers/ECU18.png",
"ECU7": "/stickers/ECU20.png",
"ECU8": "/stickers/ECU15.png",
"ECU9": "/stickers/ECU14.png",
"ECU10": "/stickers/ECU13.png",
"ECU11": "/stickers/ECU12.png",
"ECU12": "/stickers/ECU11.png",
"ECU13": "/stickers/ECU02.png",
"ECU14": "/stickers/ECU16.png",
"ECU15": "/stickers/ECU10.png",
"ECU16": "/stickers/ECU09.png",
"ECU17": "/stickers/ECU08.png",
"ECU18": "/stickers/ECU07.png",
"ECU19": "/stickers/ECU06.png",
"ECU20": "/stickers/ECU05.png",
// EGY — fotos reales validadas visualmente
"EGY1": "/stickers/EGY1.jpg",
"ENG1": "/stickers/ENG01.png",
"ENG2": "/stickers/ENG03.png",
"ENG3": "/stickers/ENG04.png",
"ENG4": "/stickers/ENG06.png",
"ENG5": "/stickers/ENG05.png",
"ENG6": "/stickers/ENG07.png",
"ENG7": "/stickers/ENG08.png",
"ENG8": "/stickers/ENG09.png",
"ENG9": "/stickers/ENG10.png",
"ENG10": "/stickers/ENG13.png",
"ENG11": "/stickers/ENG19.png",
"ENG12": "/stickers/ENG11.png",
"ENG13": "/stickers/ENG02.png",
"ENG14": "/stickers/ENG12.png",
"ENG15": "/stickers/ENG18.png",
"ENG16": "/stickers/ENG17.png",
// SIN PNG DISPONIBLE - falta subir imagen para "ENG17"
"ENG18": "/stickers/ENG16.png",
"ENG19": "/stickers/ENG15.png",
"ENG20": "/stickers/ENG14.png",
"ESP1": "/stickers/ESP01.png",
"ESP2": "/stickers/ESP03.png",
"ESP3": "/stickers/ESP20.png",
"ESP4": "/stickers/ESP19.png",
"ESP5": "/stickers/ESP18.png",
"ESP6": "/stickers/ESP17.png",
"ESP7": "/stickers/ESP16.png",
"ESP8": "/stickers/ESP15.png",
"ESP9": "/stickers/ESP14.png",
"ESP10": "/stickers/ESP13.png",
"ESP11": "/stickers/ESP12.png",
"ESP12": "/stickers/ESP11.png",
"ESP13": "/stickers/ESP02.png",
"ESP14": "/stickers/ESP10.png",
"ESP15": "/stickers/ESP04.png",
"ESP16": "/stickers/ESP07.png",
"ESP17": "/stickers/ESP06.png",
"ESP18": "/stickers/ESP05.png",
"ESP19": "/stickers/ESP08.png",
"ESP20": "/stickers/ESP09.png",
"FRA1": "/stickers/FRA01.png",
"FRA2": "/stickers/FRA03.png",
"FRA3": "/stickers/FRA20.png",
"FRA4": "/stickers/FRA19.png",
"FRA5": "/stickers/FRA18.png",
"FRA6": "/stickers/FRA17.png",
"FRA7": "/stickers/FRA16.png",
"FRA8": "/stickers/FRA15.png",
"FRA9": "/stickers/FRA13.png",
"FRA10": "/stickers/FRA12.png",
"FRA11": "/stickers/FRA11.png",
"FRA12": "/stickers/FRA10.png",
"FRA13": "/stickers/FRA02.png",
"FRA14": "/stickers/FRA14.png",
"FRA15": "/stickers/FRA09.png",
"FRA16": "/stickers/FRA08.png",
"FRA17": "/stickers/FRA07.png",
"FRA18": "/stickers/FRA06.png",
"FRA19": "/stickers/FRA05.png",
"FRA20": "/stickers/FRA04.png",
"GER1": "/stickers/GER01.png",
"GER2": "/stickers/GER10.png",
"GER3": "/stickers/GER14.png",
// SIN PNG DISPONIBLE - falta subir imagen para "GER4"
"GER5": "/stickers/GER07.png",
"GER6": "/stickers/GER05.png",
// SIN PNG DISPONIBLE - falta subir imagen para "GER7"
"GER8": "/stickers/GER02.png",
"GER9": "/stickers/GER09.png",
// SIN PNG DISPONIBLE - falta subir imagen para "GER10"
"GER11": "/stickers/GER04.png",
"GER12": "/stickers/GER06.png",
// SIN PNG DISPONIBLE - falta subir imagen para "GER13"
"GER14": "/stickers/GER12.png",
"GER15": "/stickers/GER11.png",
"GER16": "/stickers/GER03.png",
"GER17": "/stickers/GER13.png",
// SIN PNG DISPONIBLE - falta subir imagen para "GER18"
// SIN PNG DISPONIBLE - falta subir imagen para "GER19"
"GER20": "/stickers/GER08.png",
// GHA — fotos reales validadas por nombre impreso
"GHA1": "/stickers/GHA1.jpg",
"GHA3": "/stickers/GHA3.jpg",
"GHA8": "/stickers/GHA8.jpg",
"GHA9": "/stickers/GHA20.jpg",
"GHA12": "/stickers/GHA17.jpg",
"GHA13": MISSING_STICKER, // GHA13.jpg no permite confirmar el nombre impreso con suficiente confianza
"GHA17": MISSING_STICKER, // GHA17.jpg contiene a Kamaldeen Sulemana, no a André Ayew
"GHA20": MISSING_STICKER, // GHA20.jpg contiene a Abdul Issahaku Fatawu, no a Antoine Semenyo

// HAI — material real validado
"HAI1": "/stickers/HAI1.jpg",

// IRN — material real validado
"IRN1": "/stickers/IRN1.jpg",

// IRQ — fotos reales validadas por nombre impreso
"IRQ1": "/stickers/IRQ1.jpg",
"IRQ2": MISSING_STICKER, // IRQ2.jpg contiene a Youssef Amyn, no a Jalal Hassani
"IRQ3": "/stickers/IRQ14.jpg",
"IRQ4": "/stickers/IRQ4.jpg",
"IRQ5": "/stickers/IRQ17.jpg",
"IRQ7": "/stickers/IRQ7.jpg",
"IRQ9": MISSING_STICKER, // IRQ9.jpg contiene a Marko Farji, no a Zidane Iqbal
"IRQ14": "/stickers/IRQ2.jpg",
"IRQ15": "/stickers/IRQ15.jpg",
"IRQ16": "/stickers/IRQ9.jpg",
"IRQ17": MISSING_STICKER, // IRQ17.jpg contiene a Akam Hashem, no a Osama Rashid
"IRQ18": "/stickers/IRQ16.jpg",

// JOR — fotos reales validadas por nombre impreso
"JOR1": "/stickers/JOR1.jpg",
"JOR7": "/stickers/JOR7.jpg",
"JOR10": "/stickers/JOR20.jpg",
"JOR12": "/stickers/JOR16.jpg",
"JOR14": MISSING_STICKER, // JOR14.jpg contiene a Ali Olwan, no a Amer Jamous
"JOR15": MISSING_STICKER, // JOR15.jpg contiene a Yazan Al-Naimat, no a Mousa Al-Taamari
"JOR16": "/stickers/JOR15.jpg",
"JOR18": "/stickers/JOR14.jpg",
"JOR20": MISSING_STICKER, // JOR20.jpg contiene a Nizar Al-Rashdan, no a Ibrahim Sabra
"JPN1": "/stickers/JPN01.png",
"JPN2": "/stickers/JPN12.png",
"JPN3": "/stickers/JPN13.png",
"JPN4": "/stickers/JPN14.png",
"JPN5": "/stickers/JPN15.png",
"JPN6": "/stickers/JPN19.png",
"JPN7": "/stickers/JPN20.png",
"JPN8": "/stickers/JPN16.png",
"JPN9": "/stickers/JPN17.png",
"JPN10": "/stickers/JPN18.png",
"JPN11": "/stickers/JPN06.png",
"JPN12": "/stickers/JPN05.png",
"JPN13": "/stickers/JPN02.png",
"JPN14": "/stickers/JPN03.png",
"JPN15": "/stickers/JPN04.png",
"JPN16": "/stickers/JPN07.png",
"JPN17": "/stickers/JPN08.png",
"JPN18": "/stickers/JPN09.png",
"JPN19": "/stickers/JPN10.png",
"JPN20": "/stickers/JPN11.png",
"KOR1": "/stickers/KOR01.png",
"KOR2": "/stickers/KOR02.png",
"KOR3": "/stickers/KOR04.png",
// SIN PNG DISPONIBLE - falta subir imagen para "KOR4"
"KOR5": "/stickers/KOR09.png",
"KOR6": "/stickers/KOR03.png",
"KOR7": "/stickers/KOR13.png",
// SIN PNG DISPONIBLE - falta subir imagen para "KOR8"
"KOR9": "/stickers/KOR05.png",
"KOR10": "/stickers/KOR10.png",
// SIN PNG DISPONIBLE - falta subir imagen para "KOR11"
"KOR12": "/stickers/KOR06.png",
// SIN PNG DISPONIBLE - falta subir imagen para "KOR13"
"KOR14": "/stickers/KOR08.png",
"KOR15": "/stickers/KOR07.png",
// SIN PNG DISPONIBLE - falta subir imagen para "KOR16"
// SIN PNG DISPONIBLE - falta subir imagen para "KOR17"
"KOR18": "/stickers/KOR12.png",
"KOR19": "/stickers/KOR14.png",
"KOR20": "/stickers/KOR11.png",
"KSA1": "/stickers/KSA1.jpg",
"KSA7": "/stickers/KSA7.jpg",
"KSA8": "/stickers/KSA8.jpg",
"KSA14": "/stickers/KSA14.jpg",
"KSA15": "/stickers/KSA15.jpg",
"KSA16": "/stickers/KSA16.jpg",
"KSA18": "/stickers/KSA18.jpg",
"KSA19": "/stickers/KSA19.jpg",
"KSA20": "/stickers/KSA20.jpg",
"MAR1": "/stickers/MAR01.png",
"MAR2": "/stickers/MAR14.png",
// SIN PNG DISPONIBLE - falta subir imagen para "MAR3"
// SIN PNG DISPONIBLE - falta subir imagen para "MAR4"
// SIN PNG DISPONIBLE - falta subir imagen para "MAR5"
"MAR6": "/stickers/MAR15.png",
"MAR7": "/stickers/MAR13.png",
"MAR8": "/stickers/MAR10.png",
"MAR9": "/stickers/MAR09.png",
"MAR10": "/stickers/MAR12.png",
// SIN PNG DISPONIBLE - falta subir imagen para "MAR11"
"MAR12": "/stickers/MAR04.png",
"MAR13": "/stickers/MAR02.png",
"MAR14": "/stickers/MAR11.png",
"MAR15": "/stickers/MAR08.png",
"MAR16": "/stickers/MAR05.png",
"MAR17": "/stickers/MAR07.png",
// SIN PNG DISPONIBLE - falta subir imagen para "MAR18"
"MAR19": "/stickers/MAR06.png",
"MAR20": "/stickers/MAR03.png",
"MEX1": "/stickers/MEX01.png",
"MEX2": "/stickers/MEX03.png",
"MEX3": "/stickers/MEX05.png",
"MEX4": "/stickers/MEX08.png",
"MEX5": "/stickers/MEX06.png",
"MEX6": "/stickers/MEX04.png",
"MEX7": "/stickers/MEX07.png",
"MEX8": "/stickers/MEX10.png",
"MEX9": "/stickers/MEX13.png",
"MEX10": "/stickers/MEX11.png",
"MEX11": "/stickers/MEX09.png",
"MEX12": "/stickers/MEX14.png",
"MEX13": "/stickers/MEX02.png",
"MEX14": "/stickers/MEX12.png",
"MEX15": "/stickers/MEX17.png",
"MEX16": "/stickers/MEX16.png",
"MEX17": "/stickers/MEX15.png",
"MEX18": "/stickers/MEX18.png",
"MEX19": "/stickers/MEX20.png",
"MEX20": "/stickers/MEX19.png",
"NED1": "/stickers/NED01.png",
"NED2": "/stickers/NED03.png",
"NED3": "/stickers/NED15.png",
"NED4": "/stickers/NED16.png",
"NED5": "/stickers/NED18.png",
"NED6": "/stickers/NED13.png",
"NED7": "/stickers/NED19.png",
"NED8": "/stickers/NED17.png",
"NED9": "/stickers/NED14.png",
"NED10": "/stickers/NED10.png",
"NED11": "/stickers/NED09.png",
"NED12": "/stickers/NED11.png",
"NED13": "/stickers/NED02.png",
"NED14": "/stickers/NED12.png",
"NED15": "/stickers/NED08.png",
"NED16": "/stickers/NED07.png",
"NED17": "/stickers/NED04.png",
"NED18": "/stickers/NED05.png",
"NED19": "/stickers/NED06.png",
"NED20": "/stickers/NED20.png",
"NOR1": "/stickers/NOR1.jpg",
"NOR2": "/stickers/NOR2.jpg",
"NOR3": "/stickers/NOR3.jpg",
"NOR5": "/stickers/NOR5.jpg",
"NOR8": "/stickers/NOR8.jpg",
"NOR9": "/stickers/NOR9.jpg",
"NOR11": "/stickers/NOR11.jpg",
"NOR12": "/stickers/NOR12.jpg",
"NOR13": "/stickers/NOR13.jpg",
"NOR15": "/stickers/NOR15.jpg",
"NOR18": "/stickers/NOR18.jpg",
"NOR19": "/stickers/NOR19.jpg",
"NOR20": "/stickers/NOR20.jpg",
"NZL1": "/stickers/NZL1.jpg",
"PAN1": "/stickers/PAN1.jpg",
"PAN4": "/stickers/PAN4.jpg",
"PAN7": "/stickers/PAN7.jpg",
"PAN10": "/stickers/PAN10.jpg",
"PAN14": "/stickers/PAN14.jpg",
"PAN15": "/stickers/PAN15.jpg",
"PAN18": "/stickers/PAN18.jpg",
"PAN19": "/stickers/PAN19.jpg",
"PAN20": "/stickers/PAN20.jpg",
"PAR1": "/stickers/PAR1.jpg",
"POR1": "/stickers/POR01.png",
"POR2": "/stickers/POR03.png",
"POR3": "/stickers/POR17.png",
"POR4": "/stickers/POR16.png",
"POR5": "/stickers/POR15.png",
"POR6": "/stickers/POR14.png",
"POR7": "/stickers/POR13.png",
"POR8": "/stickers/POR12.png",
"POR9": "/stickers/POR11.png",
"POR10": "/stickers/POR10.png",
"POR11": "/stickers/POR09.png",
"POR12": "/stickers/POR08.png",
"POR13": "/stickers/POR02.png",
"POR14": "/stickers/POR07.png",
"POR15": "/stickers/POR04.png",
"POR16": "/stickers/POR06.png",
"POR17": "/stickers/POR05.png",
"POR18": "/stickers/POR20.png",
"POR19": "/stickers/POR19.png",
"POR20": "/stickers/POR18.png",
"QAT5": "/stickers/QAT5.jpg",
"RSA1": "/stickers/RSA01.png",
"RSA2": "/stickers/RSA02.png",
"RSA3": "/stickers/RSA03.png",
"RSA4": "/stickers/RSA04.png",
"RSA5": "/stickers/RSA05.png",
"RSA6": "/stickers/RSA06.png",
"RSA7": "/stickers/RSA07.png",
"RSA8": "/stickers/RSA08.png",
"RSA9": "/stickers/RSA09.png",
"RSA10": "/stickers/RSA10.png",
"RSA11": "/stickers/RSA11.png",
"RSA12": "/stickers/RSA12.png",
"RSA13": "/stickers/RSA13.png",
"RSA14": "/stickers/RSA14.png",
"RSA15": "/stickers/RSA15.png",
"SCO1": "/stickers/SCO1.jpg",
"SCO16": "/stickers/SCO16.jpg",
"SEN1": "/stickers/SEN01.png",
"SEN2": "/stickers/SEN03.png",
"SEN3": "/stickers/SEN04.png",
"SEN4": "/stickers/SEN05.png",
"SEN5": "/stickers/SEN06.png",
"SEN6": "/stickers/SEN07.png",
"SEN7": "/stickers/SEN08.png",
"SEN8": "/stickers/SEN09.png",
"SEN9": "/stickers/SEN10.png",
"SEN10": "/stickers/SEN11.png",
"SEN11": "/stickers/SEN12.png",
"SEN12": "/stickers/SEN13.png",
"SEN13": "/stickers/SEN02.png",
"SEN14": "/stickers/SEN14.png",
"SEN15": "/stickers/SEN15.png",
"SEN16": "/stickers/SEN16.png",
"SEN17": "/stickers/SEN17.png",
"SEN18": "/stickers/SEN18.png",
"SEN19": "/stickers/SEN19.png",
"SEN20": "/stickers/SEN20.png",
"SUI1": "/stickers/SUI1.jpg",
"SWE1": "/stickers/SWE1.jpg",
"TUN1": "/stickers/TUN1.jpg",
"URU1": "/stickers/URU1.jpg",
"URU3": "/stickers/URU3.jpg",
"URU6": "/stickers/URU6.jpg",
"URU7": "/stickers/URU7.jpg",
"URU12": "/stickers/URU12.jpg",
"URU14": "/stickers/URU14.jpg",
"URU15": "/stickers/URU15.jpg",
"URU17": "/stickers/URU17.jpg",
"URU19": "/stickers/URU19.jpg",
"URU20": "/stickers/URU20.jpg",
"USA1": "/stickers/USA1.jpg",
"UZB1": "/stickers/UZB1.jpg",
"UZB3": "/stickers/UZB3.jpg",
"UZB4": "/stickers/UZB4.jpg",
"UZB5": "/stickers/UZB5.jpg",
"UZB8": "/stickers/UZB8.jpg",
"UZB16": "/stickers/UZB16.jpg",
"UZB17": "/stickers/UZB17.jpg",
"UZB18": "/stickers/UZB18.jpg",
"UZB20": "/stickers/UZB20.jpg"
}
